src/main/java/it/ganvim/webapp/artwork/survey/SurveyCombineController.java
package it.ganvim.webapp.artwork.survey;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import it.ganvim.webapp.artwork.answer.Answer;
import it.ganvim.webapp.artwork.core.Controller;
import it.ganvim.webapp.artwork.core.Repository;
import it.ganvim.webapp.artwork.core.SingletonDate;
import it.ganvim.webapp.artwork.domainanswer.DomainAnswer;
import it.ganvim.webapp.artwork.domainquestion.DomainQuestion;
import it.ganvim.webapp.artwork.groupquestion.GroupQuestion;
import it.ganvim.webapp.artwork.question.Question;

@ManagedBean
//@ApplicationScoped
//@RequestScoped
@ViewScoped
public class SurveyCombineController extends Controller<Long, Survey> {

	private static final long serialVersionUID = 1L;

	private Survey survey;

	private List<DomainAnswer> Answers = new ArrayList<DomainAnswer>();
	private List<DomainQuestion> Questions = new ArrayList<DomainQuestion>();
	private Long NewAnswer = 0L;
	private Long NewQuestion = 0L;
	private String  NewGroupQuestion = "";

	@Inject
	private Repository<Long, Survey> surveyRepository;
	@Inject
	private Repository<Long, GroupQuestion> gqRepository;
	@Inject
	private Repository<Long, Question> qRepository;
	@Inject
	private Repository<Long, Answer> aRepository;
	@Inject
	private Repository<Long, DomainQuestion> dqRepository;
	@Inject
	private Repository<Long, DomainAnswer> daRepository;

	public void init() {
		
		//message = this.getParameters().containsKey("Messaggio") ? getParameters().get("Messaggio") : "";
		//setId(this.getParameters().containsKey("ID") ? Long.parseLong(getParameters().get("ID")) : 1L);
		
		if (this.getSd().getIdLogin().equals(0L)) {		
			//Ritorna al Login
			this.redirect("../login.xhtml");
		}
		
		this.survey = new Survey();
		this.list();
	}

	public void list() {
		this.setSurvey(surveyRepository.getbyId(this.getSd().getIdSurvey()));
		this.setQuestions(dqRepository.getAll());
		this.setAnswers(daRepository.getAll());
	}

	public void deleteGq(Long idGq) {
		
		int res = 0;

		GroupQuestion gq = new GroupQuestion();
		gq.setId(idGq);
		
		res = gqRepository.delete(gq);
		
		if(res == 0) {			
			this.getSd().setMessage("Cancellazione avvenuta correttamente");
			this.getSd().setMessSeverity(SingletonDate.MESSOK);	
		}

		if(res == -1) {				
			this.getSd().setMessage("Errore nella cancellazione");
			this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
		}

		// Redirigere la pagina
		this.redirect("associadomande.xhtml");
	}
	
	public void updateGq(Long idGq, String gqname) {
		
		int res = 0;

		GroupQuestion gq = new GroupQuestion();
		gq.setId(idGq);
		gq.setName(gqname);
		gq.setIdsurvey(survey.getId());
		
		res = gqRepository.update(gq);
		
		if(res == 0) {			
			this.getSd().setMessage("Modifica avvenuta correttamente");
			this.getSd().setMessSeverity(SingletonDate.MESSOK);	
		}

		if(res == -1) {				
			this.getSd().setMessage("Errore nella modifica");
			this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
		}

		// Redirigere la pagina
		this.redirect("associadomande.xhtml");
	}
	
public void deleteQ(Long idQ) {
		
		int res = 0;

		Question q = new Question();
		q.setId(idQ);
		
		res = qRepository.delete(q);
		
		if(res == 0) {			
			this.getSd().setMessage("Cancellazione avvenuta correttamente");
			this.getSd().setMessSeverity(SingletonDate.MESSOK);	
		}

		if(res == -1) {				
			this.getSd().setMessage("Errore nella cancellazione");
			this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
		}

		
		// Redirigere la pagina
		this.redirect("associadomande.xhtml");
	}
	
	public void addQ(Long idGQ, Long idDQ) {
		
		int res = 0;

		Question q = new Question();
		q.setIdGroupQuestion(idGQ);
		q.setIdDomainQuestion(idDQ);
		
		if(idGQ!=0 && idDQ!=0) {

			res = qRepository.add(q);

			if(res == 0) {				
				this.getSd().setMessage("Domanda aggiunta correttamente");
				this.getSd().setMessSeverity(SingletonDate.MESSOK);	
			}

			if(res == -1) {				
				this.getSd().setMessage("Errore nella modifica");
				this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
			}

			// Redirigere la pagina
			this.redirect("associadomande.xhtml");
		}
	}
	
public void deleteA(Long idA) {
		
		int res = 0;

		Answer a = new Answer();
		a.setId(idA);
		
		res = aRepository.delete(a);
		
		if(res == 0) {			
			this.getSd().setMessage("Cancellazione avvenuta correttamente");
			this.getSd().setMessSeverity(SingletonDate.MESSOK);	
		}

		if(res == -1) {				
			this.getSd().setMessage("Errore nella cancellazione");
			this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
		}

		// Redirigere la pagina
		this.redirect("associadomande.xhtml");
	}
	
public void addA(Long idQ, Long idDA ) {

	int res = 0;

	Answer a = new Answer();
	a.setIdQuestion(idQ);
	a.setIdDomainAnswer(idDA);

	if(idQ!=0 && idDA!=0) {

		res = aRepository.add(a);

		if(res == 0) {			
			this.getSd().setMessage("Risposta aggiunta correttamente");
			this.getSd().setMessSeverity(SingletonDate.MESSOK);	
		}

		if(res == -1) {				
			this.getSd().setMessage("Errore nella modifica");
			this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
		}

		// Redirigere la pagina
		this.redirect("associadomande.xhtml");
	}
}
	
	public void addGQ(Long idS, String nameGQ ) {
		
		int res = 0;

		GroupQuestion gq = new GroupQuestion();
		gq.setName(nameGQ);;
		gq.setIdsurvey(idS);;
		
		if(idS!=0) {
			res = gqRepository.add(gq);

			if(res == 0) {			
				this.getSd().setMessage("Gruppo domanda aggiunta correttamente");
				this.getSd().setMessSeverity(SingletonDate.MESSOK);	
			}

			if(res == -1) {				
				this.getSd().setMessage("Errore nella modifica");
				this.getSd().setMessSeverity(SingletonDate.MESSERROR);	
			}

			// Redirigere la pagina
			this.redirect("associadomande.xhtml");
		}
	}
	
	public void onPanelCollapsed(int panel) {	
		
		boolean[] panels = new boolean[100];
		
		for(int i=0; i<100; i++) {
			panels[i] = true;		
		}
		panels[panel] = false;
		
		this.getSd().setPanelCollapsed(panels);
		//this.getSd().setPanelCollapsed("Form:j_idt61:" + panel + ":gq");
		//this.redirect("associadomande.xhtml");
	}
	
	public boolean modified(Long idsurvey) {

		boolean res = surveyRepository.isModified(idsurvey);

		return res;
	}
	
	public Survey getSurvey() {
		return survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public Repository<Long, Question> getqRepository() {
		return qRepository;
	}

	public void setqRepository(Repository<Long, Question> qRepository) {
		this.qRepository = qRepository;
	}

	public Repository<Long, Answer> getaRepository() {
		return aRepository;
	}

	public void setaRepository(Repository<Long, Answer> aRepository) {
		this.aRepository = aRepository;
	}

	public List<DomainAnswer> getAnswers() {
		return Answers;
	}

	public void setAnswers(List<DomainAnswer> Answers) {
		this.Answers = Answers;
	}

	public List<DomainQuestion> getQuestions() {
		return Questions;
	}

	public void setQuestions(List<DomainQuestion> Questions) {
		this.Questions = Questions;
	}

	public Repository<Long, DomainQuestion> getDqRepository() {
		return dqRepository;
	}

	public void setDqRepository(Repository<Long, DomainQuestion> dqRepository) {
		this.dqRepository = dqRepository;
	}

	public Repository<Long, DomainAnswer> getDaRepository() {
		return daRepository;
	}

	public void setDaRepository(Repository<Long, DomainAnswer> daRepository) {
		this.daRepository = daRepository;
	}

	public Long getNewAnswer() {
		return NewAnswer;
	}

	public void setNewAnswer(Long newAnswer) {
		NewAnswer = newAnswer;
	}

	public Long getNewQuestion() {
		return NewQuestion;
	}

	public void setNewQuestion(Long newQuestion) {
		NewQuestion = newQuestion;
	}

	public String getNewGroupQuestion() {
		return NewGroupQuestion;
	}

	public void setNewGroupQuestion(String newGroupQuestion) {
		NewGroupQuestion = newGroupQuestion;
	}
}

src/main/webapp/pages/admin/associadomande.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">	
<h:head>
	<title>MAV | Admin</title>
<link rel="icon" href="#{resource['img/mavicon.png']}"/>
</h:head>
<h:body style=" background-color:#a0a09e;">
<h:form id="Form" style="align: center;  whith: 100%;">
  <b:container class="myjumbotron" layout="fluid" style="align: left; width: 80%;">
			<b:row layout="fluid" style="align: center; whith: 100%;">
				<b:column medium-screen="12" style="align: center;">
					<b:image name="testata" value="#{resource['img/Admin_header_white.png']}"
						tooltip="MAV"
						style=" top: 0px; left: 0px;width: 100%; height:auto; align: center;" />
				</b:column>
			</b:row>
			<b:row layout="fluid">
				<b:column medium-screen="2" span="2"
					style="align: left; height: 30px ">
				</b:column>
				<b:column medium-screen="10" span="10"
					style="align: right; text-align: right; font-size: 25px; color: white; height: 30px">
					<!-- inserire i tasti del sottomenù -->
					
					Pannello di controllo | #{surveyCombineController.sd.level}:					
					<b:dropButton look="primary"
						value="#{surveyCombineController.sd.username}">
						<b:navCommandLink  value="Profilo" action="#{surveyCombineController.myProfile()}" />
						<b:navCommandLink value="Logout" action="#{surveyCombineController.logout()}"  />
					</b:dropButton>			
				</b:column>
			</b:row>
			<b:row>
				<h:outputText value="a" style="color:#a0a09e " />
			</b:row>
			<!-- inserire i tasti del menù -->
			
			<b:row layout="fluid" style="height:520px">
				<b:column medium-screen="2" span="2"
					style="align: left; height: 30px ">
					<b:buttonGroup orientation="vertical" size="lg">
						<b:commandButton value="Utenti" look="primary" action="#{surveyCombineController.changePage('utenti.xhtml')}" style="border-radius:10px" />
							<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Domande" look="primary" action="#{surveyCombineController.changePage('domande.xhtml')}" style=" border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Risposte" look="primary" action="#{surveyCombineController.changePage('risposte.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
							
						<b:commandButton value="Email" look="primary" action="#{surveyCombineController.changePage('email.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Suggerimenti" look="primary" action="#{surveyCombineController.changePage('suggerimenti.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						
						<b:commandButton value="Questionario" look="warning" action="#{surveyCombineController.changePage('questionario.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Join Questionario" look="primary" action="#{surveyCombineController.changePage('joinquestionario.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Statistiche" look="primary" action="#{surveyCombineController.changePage('statistiche.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 30px "/>
						</b:row>
								
						</b:buttonGroup>
				</b:column>
					<b:column medium-screen="1" span="1">
					<h:outputText value="" style="color:white " />
						</b:column>
				<b:column medium-screen="9" span="9"
					style="align: center;  background-color: white; border-radius:10px ">
					<h:outputText value="a" style="color:white " />


					<!-- inserire il corpo della pagina -->

					<b:row layout="fluid">
						<b:column medium-screen="9" span="9"
							style="align: left; height: 10px; background-color: white ">
						</b:column>
					</b:row>
					<h:inputHidden value="#{surveyCombineController.survey.id}" />			
					<b:panel id="survey"
						title="Questionario: #{surveyCombineController.survey.name}"
						look="primary"  collapsible="false">
						<f:facet name="footer">
							<h:outputText value="Aggiungi gruppo:" />

							<b:inputTextarea id="newgroup"
								value="#{surveyCombineController.newGroupQuestion}" rows="2"
								size="250" style="width: 65%;" />

							<b:commandButton value="Aggungi" icon="edit"
								action="#{surveyCombineController.addGQ(surveyCombineController.survey.id,surveyCombineController.newGroupQuestion)}"
								label="Aggiungi" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}"
								 style="margin-left: 85%; margin-top: -6em;">
							</b:commandButton>
						</f:facet>

						<b:row layout="fluid">
							<b:column>
								<h:outputLabel value=" " />
							</b:column>
						</b:row>
						<ui:repeat
							value="#{surveyCombineController.survey.groupQuestions}"
							var="group" varStatus="gq">
							<!--  <b:accordion expanded-panels="#{surveyCombineController.sd.panelCollapsed}">-->
							<b:panel id="gq" title="Gruppo di Domanda n° #{gq.index+1}:" collapsed="#{surveyCombineController.sd.panelCollapsed[gq.index]}"
								look="warning" onexpanded="ajax:surveyCombineController.onPanelCollapsed(gq.index)">
								<f:facet name="footer">
									<h:outputText value="Aggiungi domanda:" />
									<b:selectOneMenu id="newquestion"
										value="#{surveyCombineController.newQuestion}" ajax="true"
										update="Form" style="width: 400px;">
										<f:selectItem itemLabel="Selezionare una domanda" itemValue="0" />
										<f:selectItems value="#{surveyCombineController.questions}"
											var="quest" itemLabel="#{quest.name}" itemValue="#{quest.id}" />
									</b:selectOneMenu>

									<b:commandButton value="Aggungi" icon="edit"
										action="#{surveyCombineController.addQ(group.id,surveyCombineController.newQuestion)}"
										label="Aggiungi" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}"
										style="margin-left: 85%; margin-top: -6em;">
									</b:commandButton>

									<h:inputHidden id="newq"
										value="#{surveyCombineController.newQuestion}" />

								</f:facet>

								<b:inputTextarea id="group" value="#{group.name}" rows="2"
									size="250" style="width: 65%;" />

								<b:commandButton value="Modifica" icon="edit"
									action="#{surveyCombineController.updateGq(group.id, group.name)}"
									label="Modifica" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}"
									style="margin-left: 68%; margin-top: -7em;" />

								<b:commandButton value="Cancella" icon="trash"
									action="#{surveyCombineController.deleteGq(group.id)}"
									label="Cancella" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}"
									style="margin-left: 85%; margin-top: -10em;">
								</b:commandButton>

								<b:row layout="fluid">
									<b:column>
										<h:outputLabel value=" " />
									</b:column>
								</b:row>

								<ui:repeat value="#{group.questions}" var="question"
									varStatus="q">

									<b:panel look="info" id="q">
										<f:facet name="footer">
											<h:outputText value="Aggiungi risposta:" />
											<b:selectOneMenu id="newanswer"
												value="#{surveyCombineController.newAnswer}" ajax="true"
												update="Form" style="width: 400px;">
												<f:selectItem itemLabel="Selezionare una risposta" itemValue="0" />
												<f:selectItems value="#{surveyCombineController.answers}"
													var="answer" itemLabel="#{answer.name}"
													itemValue="#{answer.id}" />
											</b:selectOneMenu>

											<b:commandButton value="Aggungi" icon="edit"
												action="#{surveyCombineController.addA(question.id,surveyCombineController.newAnswer)}"
												label="Aggiungi" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}"
												 style="margin-left: 85%; margin-top: -6em;">
											</b:commandButton>

											<h:inputHidden id="newa"
												value="#{surveyCombineController.newAnswer}" />


										</f:facet>
										<f:facet name="heading">

											<h:outputText
												value="Domanda n° #{q.index+1}: #{question.name}" />

										</f:facet>
										<b:row>
											<b:commandButton value="Cancella" icon="trash" offset="10"
												action="#{surveyCombineController.deleteQ(question.id)}"
												label="Cancella" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}">

											</b:commandButton>
										</b:row>
										<b:row style="color:white">a</b:row>
										<b:panel title="Risposte:" look="success" id="a" collapse="false">

											<ui:repeat value="#{question.answers}" var="answer"
												varStatus="a">

												<b:panel look="success" collapsible="false">
													<f:facet name="heading">
														<h:outputText value="- #{answer.name}" />
													</f:facet>
													<b:commandButton value="Cancella" icon="trash" offset="10"
														action="#{surveyCombineController.deleteA(answer.id)}"
														label="Cancella" disabled="#{!surveyCombineController.modified(surveyCombineController.survey.id)}">
													</b:commandButton>
												</b:panel>

											</ui:repeat>
										</b:panel>
									</b:panel>
								</ui:repeat>
							</b:panel>
							<!-- </b:accordion>-->
						</ui:repeat>
					</b:panel>
					
						<b:alert severity="#{surveyCombineController.sd.messSeverity}" 
						rendered="#{surveyCombineController.sd.message.length()!=0}" style="width:100%;"> 
						#{surveyCombineController.sd.message} </b:alert>
					<h:outputLabel />

					<h:outputText value="a" style="color:white " />
				</b:column>
			</b:row>
			<!-- inserire il piede della pagina -->

			<b:row>
				<b:column>
					<h:outputText value="a" style="color:#a0a09e " />
				</b:column>
			</b:row>

			<b:row layout="fluid"
				style="align: center; width: 100%; padding-top: 3%">

				<b:column span="1" style="text-align: right">
					<b:image name="maps" value="#{resource['img/maps.png']}"/>
				</b:column>

				<b:column class="hind" span="2"
					style="text-align: left;  font-weight: 600; font-size: 12px; color:white">
					<p>
						DOVE SIAMO | LOCATION<br></br> Indirizzo | Address<br></br> Via IV
						Novembre 44<br></br> 80056 – Ercolano (NA)<br></br> <br></br>
					</p>
				</b:column>

				<b:column class="hind" span="4"
					style="text-align: left; font-weight: 600; font-size: 12px; color:white">
					<p>
						<br></br> Contatti | Info<br></br> Mail: info@museomav.it<br></br>
						Tel: 081/7776843 - 081/7776784 | Fax: 081/7323941
					</p>
				</b:column>
				<b:column span="5"></b:column>
			</b:row>


			<b:row layout="fluid"
				style="align: center; width: 100%; padding-top: 1%">
				<b:column class="hind" span="12"
					style="text-align: center; font-weight: 600; font-size: 12px; color:white">
				
 				 ©2018 MAV | GANViM
				
 				</b:column>
			</b:row>

		</b:container>
	</h:form>
</h:body>
</html>

src/main/webapp/pages/admin/suggerimenti.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:b="http://bootsfaces.net/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
<h:head>
	<title>MAV | Admin</title>
<link rel="icon" href="#{resource['img/mavicon.png']}" />
</h:head>
<h:body style=" background-color:#a0a09e;">
<h:form id="Form" style="align: center;  whith: 100%;">
  <b:container class="myjumbotron" layout="fluid" style="align: left; width: 80%;">
			<b:row layout="fluid" style="align: center; whith: 100%;">
				<b:column medium-screen="12" style="align: center;">
					<b:image name="testata" value="#{resource['img/Admin_header_white.png']}"
						tooltip="MAV"
						style=" top: 0px; left: 0px;width: 100%; height:auto; align: center;" />
				</b:column>
			</b:row>
			<b:row layout="fluid">
				<b:column medium-screen="2" span="2"
					style="align: left; height: 30px ">
				</b:column>
				<b:column medium-screen="10" span="10"
					style="align: right; text-align: right; font-size: 25px; color: white; height: 30px">
					<!-- inserire i tasti del sottomenù -->
					
					Pannello di controllo | #{suggestController.sd.level}:					
					<b:dropButton look="primary"
						value="#{suggestController.sd.username}">
						<b:navCommandLink  value="Profilo" action="#{suggestController.myProfile()}" />
						<b:navCommandLink value="Logout" action="#{suggestController.logout()}"  />
					</b:dropButton>			
				</b:column>
			</b:row>
			<b:row>
				<h:outputText value="a" style="color:#a0a09e " />
			</b:row>
			<!-- inserire i tasti del menù -->
			
			<b:row layout="fluid" style="height:520px">
				<b:column medium-screen="2" span="2"
					style="align: left; height: 30px ">
					<b:buttonGroup orientation="vertical" size="lg">
						<b:commandButton value="Utenti" look="primary" action="#{suggestController.changePage('utenti.xhtml')}" style="border-radius:10px" />
							<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Domande" look="primary" action="#{suggestController.changePage('domande.xhtml')}" style=" border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Risposte" look="primary" action="#{suggestController.changePage('risposte.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
							
						<b:commandButton value="Email" look="primary" action="#{suggestController.changePage('email.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Suggerimenti" look="warning" action="#{suggestController.changePage('suggerimenti.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						
						<b:commandButton value="Questionario" look="primary" action="#{suggestController.changePage('questionario.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Join Questionario" look="primary" action="#{suggestController.changePage('joinquestionario.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:commandButton value="Statistiche" look="primary" action="#{suggestController.changePage('statistiche.xhtml')}" style="border-radius:10px" />
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 20px "/>
						</b:row>
						<b:row layout="fluid">
						<b:column medium-screen="2" span="2"
						style="align: left; height: 30px "/>
						</b:row>
								
						</b:buttonGroup>
				</b:column>
					<b:column medium-screen="1" span="1">
					<h:outputText value="" style="color:white " />
						</b:column>
				<b:column medium-screen="9" span="9"
					style="align: center;  background-color: white; border-radius:10px ">
					<h:outputText value="a" style="color:white " />

					<!-- inserire il corpo della pagina -->

					<h:form>
						<b:dataTable value="#{suggestController.suggests}" var="suggest"
							excel="true" csv="true" pdf="true" columnVisibility="true"
							copy="true" print="true">
							<b:dataTableColumn value="#{suggest.suggest}"
								label="suggerimenti" order="asc" />

						</b:dataTable>
					</h:form>
					<h:outputText value="a" style="color:white " />
				</b:column>
			</b:row>
			<b:row layout="fluid">
				<b:column medium-screen="9" span="9"
					style="align: left; height: 10px ">
				</b:column>
			</b:row>
			<!-- inserire il piede della pagina -->

<b:row layout="fluid" style="align: center; width: 100%; padding-top: 3%">

				<b:column span="1" style="text-align: right">
					<b:image name="maps" value="#{resource['img/maps.png']}"/>
				</b:column>

				<b:column class="hind" span="2" style="text-align: left;  font-weight: 600; font-size: 12px; color:white">
					<p>
						DOVE SIAMO | LOCATION<br></br> Indirizzo | Address<br></br> Via IV
						Novembre 44<br></br> 80056 – Ercolano (NA)<br></br> <br></br>
					</p>
				</b:column>

				<b:column class="hind" span="4" style="text-align: left; font-weight: 600; font-size: 12px; color:white">
					<p>
						<br></br> Contatti | Info<br></br> Mail: info@museomav.it<br></br>
						Tel: 081/7776843 - 081/7776784 |  Fax: 081/7323941
					</p>
				</b:column>
				<b:column span="5"></b:column>
			</b:row>


			<b:row layout="fluid" style="align: center; width: 100%; padding-top: 1%">
				<b:column class="hind" span="12" style="text-align: center; font-weight: 600; font-size: 12px; color:white">
				
 				 ©2018 MAV | GANViM
				
 				</b:column>
			</b:row>

		</b:container>
	</h:form>
</h:body>
</html>